"""Local fixture observations aligned to CardNav / PriceAI public samples. No network."""
from __future__ import annotations

FIXTURE_ROWS = [
    {
        "normalized_site": "huasheng",
        "source_id": "priceai-channels",
        "source_class": "aggregator",
        "source_priority": 30,
        "platform_family": "ChatGPT",
        "model_or_plan": "chatgpt-basic-account",
        "price": 0.3,
        "currency": "CNY",
        "billing_unit": "account",
        "stock_status": "in_stock",
        "region": "",
        "payment_tags": "alipay",
        "delivery_tags": "account",
        "public_perf": "",
        "observed_at": "2026-08-27T22:55:00.000Z",
        "provenance": "fixture:priceai-channels",
        "confidence": 0.6,
        "html": "<should-be-stripped>",
    },
    {
        "normalized_site": "huasheng",
        "source_id": "openprice-products",
        "source_class": "aggregator",
        "source_priority": 10,
        "platform_family": "ChatGPT",
        "model_or_plan": "chatgpt-basic-account",
        "price": 0.5,
        "currency": "CNY",
        "billing_unit": "account",
        "stock_status": "in_stock",
        "region": "CN",
        "payment_tags": "",
        "delivery_tags": "",
        "public_perf": "",
        "observed_at": "2026-08-27T22:55:00.000Z",
        "provenance": "fixture:openprice-products",
        "confidence": 0.4,
    },
    {
        "normalized_site": "mufeng",
        "source_id": "cardnav-home",
        "source_class": "aggregator",
        "source_priority": 20,
        "platform_family": "Claude",
        "model_or_plan": "claude-pro",
        "price": 128,
        "currency": "CNY",
        "billing_unit": "month",
        "stock_status": "in_stock",
        "region": "",
        "payment_tags": "",
        "delivery_tags": "subscription",
        "public_perf": "",
        "observed_at": "2026-08-27T22:55:00.000Z",
        "provenance": "fixture:cardnav-home",
        "confidence": 0.5,
    },
    {
        "normalized_site": "mufeng",
        "source_id": "priceai-channels",
        "source_class": "aggregator",
        "source_priority": 30,
        "platform_family": "Claude",
        "model_or_plan": "claude-pro",
        "price": 99,
        "currency": "CNY",
        "billing_unit": "month",
        "stock_status": "in_stock",
        "region": "",
        "payment_tags": "alipay",
        "delivery_tags": "subscription",
        "public_perf": "",
        "observed_at": "2026-08-27T22:55:00.000Z",
        "provenance": "fixture:priceai-channels",
        "confidence": 0.6,
    },
    {
        "normalized_site": "lingxi-ai",
        "source_id": "lingxi-api",
        "source_class": "site_api",
        "source_priority": 40,
        "platform_family": "GPT",
        "model_or_plan": "gpt-4o",
        "price": 1.2,
        "currency": "USD",
        "billing_unit": "1m-tokens",
        "stock_status": "online",
        "region": "",
        "payment_tags": "crypto",
        "delivery_tags": "api",
        "public_perf": "",
        "observed_at": "2026-08-27T22:55:00.000Z",
        "provenance": "fixture:lingxi-api",
        "confidence": 0.7,
    },
    {
        "normalized_site": "lingxi-ai",
        "source_id": "cardnav-home",
        "source_class": "aggregator",
        "source_priority": 20,
        "platform_family": "GPT",
        "model_or_plan": "gpt-4o",
        "price": 2.0,
        "currency": "USD",
        "billing_unit": "1m-tokens",
        "stock_status": "online",
        "region": "",
        "payment_tags": "",
        "delivery_tags": "api",
        "public_perf": "",
        "observed_at": "2026-08-27T22:55:00.000Z",
        "provenance": "fixture:cardnav-home",
        "confidence": 0.5,
    },
]


def fixtures_for_source(source_id: str) -> list[dict]:
    return [dict(row) for row in FIXTURE_ROWS if row["source_id"] == source_id]
